server:
  port: 9999
  # Undertow配置
  undertow:
    accesslog:
      # 开启Undertow访问日志
      enabled: true
      dir: /data/logs

info:
  component: Discovery Service
  description: Discovery service based on Netflix Eureka

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 30000
    renewalPercentThreshold: 0.49
    renewalThresholdUpdateIntervalMs: 60000

logging:
  level:
    root: INFO